name: docs

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  docs:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - run: pip install mkdocs-material==8.5.3
    - run: mkdocs gh-deploy --force
